#go to https://www.baseball-reference.com/teams/NYY/2019-schedule-scores.shtml, click modify table to scrape data
#use https://www.textfixer.com/tools/remove-line-breaks.php to remove line breaks

teams = "BAL BAL BAL DET DET DET BAL BAL BAL HOU HOU HOU CHW CHW CHW BOS BOS KCR KCR KCR KCR LAA LAA LAA LAA SFG SFG SFG ARI ARI MIN MIN MIN SEA SEA SEA SEA TBR TBR TBR BAL BAL TBR TBR TBR BAL BAL BAL BAL KCR KCR KCR SDP SDP SDP BOS BOS BOS TOR TOR TOR CLE CLE CLE NYM NYM CHW CHW CHW CHW TBR TBR TBR HOU HOU HOU HOU TOR TOR TOR BOS BOS NYM NYM TBR TBR TBR TBR TOR TOR TOR TBR TBR TBR TBR COL COL COL MIN MIN MIN BOS BOS BOS BOS ARI ARI BOS BOS BOS BOS BAL BAL BAL TOR TOR TOR TOR BAL BAL BAL BAL CLE CLE CLE CLE OAK OAK OAK LAD LAD LAD SEA SEA SEA OAK OAK OAK TEX TEX TEX BOS BOS BOS BOS DET DET DET TOR TOR TOR LAA LAA LAA TOR TOR TOR TBR TBR TEX TEX TEX"
split = teams.split(" ")

print(split)